apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{PROJECT_NAME}}-staging

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: staging

replicas:
  - name: {{PROJECT_NAME}}
    count: 2

patches:
  - target:
      kind: Deployment
      name: {{PROJECT_NAME}}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

  - target:
      kind: Ingress
      name: {{PROJECT_NAME}}
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "{{PROJECT_NAME}}-staging.local"

configMapGenerator:
  - name: {{PROJECT_NAME}}-config
    behavior: merge
    literals:
      - logging.level=DEBUG

images:
  - name: {{REGISTRY_URL}}/{{PROJECT_NAME}}
    newTag: latest
