apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: {{PROJECT_NAME}}

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/managed-by: blissful-infra

images:
  - name: {{REGISTRY_URL}}/{{PROJECT_NAME}}
    newTag: latest
