apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}
  labels:
    app: {{PROJECT_NAME}}
    app.kubernetes.io/name: {{PROJECT_NAME}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{PROJECT_NAME}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{PROJECT_NAME}}
  labels:
    app: {{PROJECT_NAME}}
